apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - workload.yaml
configMapGenerator:
  - name: cluster-health-assessor-script
    namespace: agent-health-system
    files:
      - assessor.py
generatorOptions:
  labels:
    app.kubernetes.io/name: cluster-health-assessor
