apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kagent
resources:
  - manifests.yaml
configMapGenerator:
  - name: maf-harness-poc-app
    files:
      - run.py
      - requirements.txt
generatorOptions:
  disableNameSuffixHash: true
