apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - cronjob.yaml
configMapGenerator:
  - name: cluster-health-publisher-script
    namespace: cluster-health-system
    files:
      - publisher.py
generatorOptions:
  labels:
    app.kubernetes.io/name: cluster-health-publisher
