---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: grafana-kafka-alerts
  namespace: "{{ARGO_EVENTS_NAMESPACE}}"
  labels:
    app.kubernetes.io/part-of: grafana-kafka-alert-verification
spec:
  template:
    serviceAccountName: "{{ARGO_EVENTS_SERVICE_ACCOUNT}}"
  kafka:
    grafana-alerts:
      url: "{{CONFLUENT_BOOTSTRAP}}"
      topic: "{{CONFLUENT_TOPIC}}"
      consumerGroup:
        groupName: "{{CONSUMER_GROUP_PREFIX}}-grafana-alerts"
      tls:
        caCertSecret:
          name: "{{CONFLUENT_CA_SECRET_NAME}}"
          key: ca.pem
      sasl:
        mechanism: "PLAIN"
        userSecret:
          name: "{{CONFLUENT_CREDENTIALS_SECRET_NAME}}"
          key: key
        passwordSecret:
          name: "{{CONFLUENT_CREDENTIALS_SECRET_NAME}}"
          key: secret
      jsonBody: true
      partition: ""
      version: "2.5.0"
